# SPDX-FileCopyrightText: 2026 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: CC0-1.0

border: rounded
color:
  help:
    usage: bold
    command: white dim
    option: white dim
    description: italic
  url: cyan italic
  current-url: white dim italic
  missed-url: red italic strike
  error: red

plugins:
  env:
    enable: true
    order: 4
    hotkey: CTRL-E

  git-worktrees:
    enable: true
    order: 3
    hotkey: CTRL-G
    color:
      clean: bright_green
      untracked: green dim
      modified: yellow
      staged: cyan
      conflict: bright_red underline
      detached: magenta strike italic
      rebase: bright_blue italic
      merge: bright_blue italic
      cherry_pick: bright_magenta italic
      revert: bright_cyan italic
      bisect: bright_white italic

  mc-hotlist:
    enable: true
    order: 1
    hotkey: CTRL-H

  recent:
    enable: true
    order: 2
    hotkey: CTRL-T
