# SPDX-FileCopyrightText: 2026 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

$schema: https://json-schema.org/draft/2020-12/schema
$id: https://github.com/zaufi/cdui/config.schema.yaml
title: CDUI Configuration

type: object
additionalProperties: false

properties:
  border:
    type: string
    # NOTE See `man sk` for `--border` option.
    enum:
      - none
      - plain
      - rounded
      - double
      - thick
      - light-double-dashed
      - heavy-double-dashed
      - light-triple-dashed
      - heavy-triple-dashed
      - light-quadruple-dashed
      - heavy-quadruple-dashed
      - quadrant-inside
      - quadrant-outside
    default: rounded

  color:
    type: object
    additionalProperties: false

    properties:

      error: &error
        type: string
        default: red

      url:
        type: string
        default: cyan

      current-url: &white
        type: string
        default: white

      missed-url: *error

      help:
        type: object
        additionalProperties: false
        properties:

          usage:
            type: string
            default: bold

          option: *white
          command: *white

          description:
            type: string
            default: italic

  plugins:
    type: object
    additionalProperties: false

    patternProperties:
      ^[a-z0-9]+(-[a-z0-9]+)*$:
        type: object
        additionalProperties: true
        properties:
          enable:
            type: boolean
          order:
            type: integer
            minimum: 1
          hotkey:
            type: string
            pattern: ^CTRL-[A-Z]$
